## Name: Taseng Mancheykhun
## PRN no: 240840141021

In [16]:
import numpy as np     #importing numpy library as short form np

1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [2]:
print(np.__version__)     # get numpy verion
print(np.show_config())   # show numpy build configuration

2.1.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.

2. Write a NumPy program to get help on the add function.

In [12]:
help(np.add)    #getting help on add function

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [13]:
a=np.array([2,3,5,4,7,1])  
np.all(a)    # np.all() function gives True when all elements are non-zero

np.True_

4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [14]:
a=np.array([0,0,0,1])
np.any(a)     # np.any() function gives False if all the function is zero and gives true if even one element is non-zero

np.True_

5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [7]:
np.isfinite(a)  # Gives True for each element if they are finite 

array([ True,  True,  True,  True])

6. Write a NumPy program to test element-wise for positive or negative infinity.

In [20]:
b=np.array([1,2,np.inf, -np.inf,-8])             
pos_inf = np.isposinf(b)                    #Gives True for positive infinity
neg_inf = np.isneginf(b)                    #Gives True for negative infinity

# Print the results
print(f"Original array {b}")
print(f"Element-wise positive infinity check: {pos_inf}")
print(f"Element-wise negative infinity check: {neg_inf}") 

Original array [  1.   2.  inf -inf  -8.]
Element-wise positive infinity check: [False False  True False False]
Element-wise negative infinity check: [False False False  True False]


7. Write a NumPy program to test element-wise for NaN of a given array.

In [27]:
b=np.array([1, 2, np.inf, -np.inf, np.nan, -8])       

result=np.isnan(b)         # Gives True if element in the array is NaN

print(f"Array is {b}")

print(f"Check element-wise for NaN: {result}")

Array is [  1.   2.  inf -inf  nan  -8.]
Check element-wise for NaN: [False False False False  True False]


8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [26]:
b=np.array([5.5,45,2,1+1j,3])                 
print(f"Checking complex number element wise in {b}: ")
print(np.iscomplex(b))                                          # checks element-wise for complex number

print()
print(f"Checking real number element wise in {b}: ")
print(np.isreal(b))                                             # checks element-wise for real number

print()
print(f"Checking whether {b[0]} is scalar type or not?: ")
print(np.isscalar(b[0]))                                        # checks whether number is scalar 

print()
print(f"Checking whether {b} is scalar type or not?: ")
print(np.isscalar(b))                                            

Checking complex number element wise in [ 5.5+0.j 45. +0.j  2. +0.j  1. +1.j  3. +0.j]: 
[False False False  True False]

Checking real number element wise in [ 5.5+0.j 45. +0.j  2. +0.j  1. +1.j  3. +0.j]: 
[ True  True  True False  True]

Checking whether (5.5+0j) is scalar type or not?: 
True

Checking whether [ 5.5+0.j 45. +0.j  2. +0.j  1. +1.j  3. +0.j] is scalar type or not?: 
False


9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
less_equal) of two given arrays.

In [29]:
a=np.array([23,21,8,45,6,78])
b=np.array([21,6,77,23,41,90])

print(f"Element wise comparison of two arrays {a} and {b} for greater than: ")
print(np.greater(a,b))                     # checks element wise whether a's element is greater than b's

print()
print(f"Element wise comparison of two arrays {a} and {b} for greater than or equal to: ")
print(np.greater_equal(a,b))               # checks element wise whether a's element is greater than or equal to b's

print()
print(f"Element wise comparison of two arrays {a} and {b} for less than: ")
print(np.less(a,b))                        # checks element wise whether a's element is less than b's

print()
print(f"Element wise comparison of two arrays {a} and {b} for less than or equal to: ")
print(np.less_equal(a,b))                   # checks element wise whether a's element is less than or equal to b's


Element wise comparison of two arrays [23 21  8 45  6 78] and [21  6 77 23 41 90] for greater than: 
[ True  True False  True False False]

Element wise comparison of two arrays [23 21  8 45  6 78] and [21  6 77 23 41 90] for greater than or equal to: 
[ True  True False  True False False]

Element wise comparison of two arrays [23 21  8 45  6 78] and [21  6 77 23 41 90] for less than: 
[False False  True False  True  True]

Element wise comparison of two arrays [23 21  8 45  6 78] and [21  6 77 23 41 90] for less than or equal to: 
[False False  True False  True  True]


### 10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [30]:
a = np.array([1,7,13,105])

print(f"The size of the memory occupied by the array {a} is: ")
print("8 bytes in 64 bit system for each element: ")
print(a.size*a.itemsize)        # memory size of each element in 64 bit system i.e 8 Bytes x number of items

The size of the memory occupied by the array [  1   7  13 105] is: 
8 bytes in 64 bit system for each element: 
32


11. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [13]:
print(f"Array of 10 zeros: ")
a=np.zeros(10)                       #creates array of zeros
print(a)

print(f"Array of 10 ones: ")
a=np.ones(10)                        #creates array of ones
print(a)

print(f"Array of 10 fives: ")
a=np.ones(10)*5                     
print(a)


Array of 10 zeros: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: 
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


12. Write a NumPy program to create an array of the integers from 30 to70.

In [31]:
print("Array of integers from 30 to 70 is: ")
print()     
a=np.arange(30,70+1)                           #creates array of integers for the range given
print(a)

Array of integers from 30 to 70 is: 

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


13. Write a NumPy program to create an array of all the even integers from 30 to 70.

In [33]:
print("Array of integers of all even integers from 30 to 70 is: ")
print()
a=np.arange(30,70+1,2)                     
print(a)

Array of integers of all even integers from 30 to 70 is: 

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


14. Write a NumPy program to create a 3x3 identity matrix.

In [34]:
print("3x3 identity matrix: ")
print()
a=np.identity(3)                    #creates identity matrix of size 3 by 3
print(a)

3x3 identity matrix: 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


15. Write a NumPy program to generate a random number between 0 and 1.

In [36]:
print("Generate a random number between 0 and 1")
print()                      
a=np.random.random()               #gives a random number between 0 and 1
print(a)

Generate a random number between 0 and 1

0.01660663976240906


16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [37]:
print("Generate an array of 15 random numbers from a standard normal distribution: ")
print()
a=np.random.normal(5,2,15)       
print(a)

Generate an array of 15 random numbers from a standard normal distribution: 

[6.4714537  4.84648942 7.57495669 5.05117984 6.13007353 4.57487858
 2.61172907 7.37372508 5.3290644  0.7091442  4.9328398  6.89843545
 5.9478824  6.2282858  4.93821818]


17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.

In [38]:
a=np.arange(16,55)

print(f"Vector with values ranging from 16 to 54: ")
print()
print(a)

Vector with values ranging from 16 to 54: 

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


18. Write a NumPy program to create a 3x4 array.

In [41]:
a=np.arange(1,13).reshape(3,4)

print(f"Array of size 3x4:")
print()
print(a)

Array of size 3x4:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


19. Write a NumPy program to create a vector of length 10 with values evenly distributed
between 5 and 50.

In [42]:
a = np.linspace(6, 49, 10)

print(f"Vector of length 10 with values evenly distributed between 5 and 50: ")
print()
print(a)

Vector of length 10 with values evenly distributed between 5 and 50: 

[ 6.         10.77777778 15.55555556 20.33333333 25.11111111 29.88888889
 34.66666667 39.44444444 44.22222222 49.        ]


20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
numbers in the range from 9 to 15.

In [48]:
a = np.arange(21)            #create a vector with values from 0 to 20
print("Array is :")
print(a)
a[(a>=9)&(a<=15)] *= -1       #changing the sign of the numbers in between
print()
print("After changing the sign of numbers in the range from 9 to 15: ")
print(a)

Array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

After changing the sign of numbers in the range from 9 to 15: 
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [34]:
a = np.random.randint(0,11,5)            
print(a)

[10  1  9  4  1]


22. Write a NumPy program to multiply the values of two given vectors.

In [39]:
a = np.array([4, 8, 7, 5])
print(f"a = {a}")

b = np.array([7, 9,17, 45])
print(f"b = {b}")

result=a*b

print(f"The resultant vector is {result}")

a = [4 8 7 5]
b = [ 7  9 17 45]
The resultant vector is [ 28  72 119 225]


23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [54]:
a = np.arange(10,22).reshape((3,4))
print("3x4 matrix filled with values from 10 to 21 is: ")
print()
print(a)

3x4 matrix filled with values from 10 to 21 is: 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


24. Write a NumPy program to find the number of rows and columns of a given matrix.

In [56]:
a = np.arange(10,22).reshape((3,4))
print("3x4 matrix filled with values from 10 to 21 is: ")
print()
print(a)

print()
print(f"The shape of the matrix is {a.shape}")

3x4 matrix filled with values from 10 to 21 is: 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

The shape of the matrix is (3, 4)


25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [46]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
equal to 1, and inside 0.

In [52]:
a=np.ones((10, 10))
a[1:-1,1:-1]=0
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.

In [59]:
a=np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [63]:
a=np.random.random((3,3,3))
print(a)

[[[0.69242316 0.57593785 0.04187815]
  [0.14412682 0.74499348 0.80350398]
  [0.45045212 0.02160469 0.32059086]]

 [[0.82713915 0.29678566 0.56433401]
  [0.57258896 0.98013937 0.08285067]
  [0.72384848 0.08289661 0.53794507]]

 [[0.43345774 0.89702002 0.78122222]
  [0.70990062 0.0710332  0.39652397]
  [0.99772787 0.76516548 0.62974559]]]


29. Write a NumPy program to compute the inner product of two given vectors.

In [66]:
a=np.array([2,3,4,5,6,7])
b=np.array([4,6,8,2,8,2])

c=np.dot(a,b)
print(f"Inner product of {a} and {b} is: ")
print(c)


Inner product of [2 3 4 5 6 7] and [4 6 8 2 8 2] is: 
130


30. Write a NumPy program to sort a given array by row and column in ascending order.

In [73]:
b=np.array([[4,6,8,2,8,2],[5,6,78,23,5,15],[34,5,19,17,32,14]])
print(b)

print()
print(f"Sorting by row in ascending order: ")
print(np.sort(b))

print()
print(f"Sorting by column in ascending order: ")
print(np.sort(b, axis=0))

[[ 4  6  8  2  8  2]
 [ 5  6 78 23  5 15]
 [34  5 19 17 32 14]]

Sorting by row in ascending order: 
[[ 2  2  4  6  8  8]
 [ 5  5  6 15 23 78]
 [ 5 14 17 19 32 34]]

Sorting by column in ascending order: 
[[ 4  5  8  2  5  2]
 [ 5  6 19 17  8 14]
 [34  6 78 23 32 15]]


31. Write a NumPy program to extract all numbers from a given array which are less and greater
than a specified number.

In [50]:
a=np.array([4,6,8,2,8,23,87,54,17,11,32,64])
print(f"Given array is {a}")

print()
print(f"Numbers which are less than 10 are: ")
c=np.extract(a<10,a)
print(c)

print()
print(f"Numbers which are greater than 10 are: ")
d=np.extract(a>10,a)
print(d)

Given array is [ 4  6  8  2  8 23 87 54 17 11 32 64]

Numbers which are less than 10 are: 
[4 6 8 2 8]

Numbers which are greater than 10 are: 
[23 87 54 17 11 32 64]


32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a
given number.

In [51]:
a=np.array([4,6,8,2,8,23,87,54,2,11,32,64])
print(f"Given array is: {a}")

print()
print("Replacing numbers equal to 2: ")
b=np.where(a==2, 333, a)
print(b)

print()
print("Replacing numbers less than 5: ")
b=np.where(a<5, 11, a)
print(b)

print()
print("Replacing numbers greater than 10: ")
a=np.where(a>10, 22, a)
print(a)

Given array is: [ 4  6  8  2  8 23 87 54  2 11 32 64]

Replacing numbers equal to 2: 
[  4   6   8 333   8  23  87  54 333  11  32  64]

Replacing numbers less than 5: 
[11  6  8 11  8 23 87 54 11 11 32 64]

Replacing numbers greater than 10: 
[ 4  6  8  2  8 22 22 22  2 22 22 22]


33. Write a NumPy program to create an array of equal shape and data type of a given array.

In [52]:
a=np.array([12.0,34,5,6,77,8,9,10])

b=np.ones_like(a)*3      #creates an array of equal shape
print(b)

[3. 3. 3. 3. 3. 3. 3. 3.]


34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a
variable.

In [53]:
#a=np.arange(60).reshape(3,5,4)
a=np.random.random((3,5,4))
print(f"Three-dimension array with shape (3,5,4): ")
print()
print(a)

Three-dimension array with shape (3,5,4): 

[[[0.62750073 0.185772   0.62784977 0.75248412]
  [0.65918833 0.26983928 0.63723581 0.50666092]
  [0.86070989 0.13854375 0.44800702 0.35666011]
  [0.96123657 0.06497293 0.75782389 0.42437934]
  [0.60415168 0.64053957 0.2906912  0.4565092 ]]

 [[0.97332024 0.61736112 0.94137086 0.0643402 ]
  [0.82185843 0.92860814 0.18900357 0.28995781]
  [0.64979555 0.68339229 0.46603764 0.86316302]
  [0.84260327 0.61385012 0.48845409 0.15396118]
  [0.42089668 0.20327858 0.06903331 0.3600542 ]]

 [[0.15317969 0.43882525 0.81601938 0.96463488]
  [0.38971026 0.37398676 0.01856306 0.6948712 ]
  [0.40373895 0.03359419 0.59473043 0.7518242 ]
  [0.11925007 0.02609346 0.43321219 0.79294059]
  [0.68289664 0.54644189 0.19573938 0.59654356]]]


35. Write a NumPy program to multiply two given arrays of same size element-by-element.

In [105]:
print(f"Matrix A: ")
a=np.arange(12).reshape(3,4)
print(a)

print()
print(f"Matrix B: ")
b=np.arange(24,36).reshape(3,4)
print(b)

print()
print(f"Resultant matrix C: ")
c=np.multiply(a,b)
print(c)

Matrix A: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Matrix B: 
[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]

Resultant matrix C: 
[[  0  25  52  81]
 [112 145 180 217]
 [256 297 340 385]]
